import { MigrationInterface, QueryRunner } from "typeorm";

export class InitialMigration1767146908518 implements MigrationInterface {
    name = 'InitialMigration1767146908518'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TYPE "public"."seat_status_state_enum" AS ENUM('available', 'booked', 'locked', 'reserved')`);
        await queryRunner.query(`CREATE TABLE "seat_status" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "trip_id" uuid NOT NULL, "seat_id" uuid NOT NULL, "booking_id" uuid, "state" "public"."seat_status_state_enum" NOT NULL DEFAULT 'available', "locked_until" TIMESTAMP WITH TIME ZONE, CONSTRAINT "PK_1130421736afc3c987cb46a6f2a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."seats_seattype_enum" AS ENUM('normal', 'vip', 'business')`);
        await queryRunner.query(`CREATE TABLE "seats" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bus_id" uuid NOT NULL, "seat_code" character varying NOT NULL, "seatType" "public"."seats_seattype_enum" NOT NULL DEFAULT 'normal', "is_active" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_3fbc74bb4638600c506dcb777a7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."seat_layouts_layouttype_enum" AS ENUM('standard_2x2', 'standard_2x3', 'vip_1x2', 'sleeper_1x2', 'custom')`);
        await queryRunner.query(`CREATE TABLE "seat_layouts" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "bus_id" uuid NOT NULL, "layoutType" "public"."seat_layouts_layouttype_enum" NOT NULL DEFAULT 'standard_2x2', "total_rows" integer NOT NULL, "seats_per_row" integer NOT NULL, "layout_config" json NOT NULL, "seat_pricing" json NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_248f4bfc8320776a1a4217c7f50" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_seat_layouts_bus_id" ON "seat_layouts" ("bus_id") `);
        await queryRunner.query(`CREATE INDEX "idx_seat_layouts_type" ON "seat_layouts" ("layoutType") `);
        await queryRunner.query(`CREATE INDEX "idx_seat_layouts_created_at" ON "seat_layouts" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_seat_layouts_bus_type" ON "seat_layouts" ("bus_id", "layoutType") `);
        await queryRunner.query(`CREATE TABLE "buses" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "operator_id" uuid NOT NULL, "plate_number" character varying NOT NULL, "model" character varying NOT NULL, "seat_capacity" integer NOT NULL, "amenities_json" json, CONSTRAINT "UQ_3f4ba55c6743181511a419c3b80" UNIQUE ("plate_number"), CONSTRAINT "PK_ddebc0eeba64a019ae072975947" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_buses_operator_id" ON "buses" ("operator_id") `);
        await queryRunner.query(`CREATE INDEX "idx_buses_plate_number" ON "buses" ("plate_number") `);
        await queryRunner.query(`CREATE INDEX "idx_buses_model" ON "buses" ("model") `);
        await queryRunner.query(`CREATE INDEX "idx_buses_operator_capacity" ON "buses" ("operator_id", "seat_capacity") `);
        await queryRunner.query(`CREATE INDEX "idx_buses_operator_model" ON "buses" ("operator_id", "model") `);
        await queryRunner.query(`CREATE TYPE "public"."operators_status_enum" AS ENUM('pending', 'approved', 'suspended')`);
        await queryRunner.query(`CREATE TABLE "operators" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "contact_email" character varying NOT NULL, "contact_phone" character varying NOT NULL, "status" "public"."operators_status_enum" NOT NULL DEFAULT 'pending', "approved_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_b6e94f1512bebbc88e901f01b04" UNIQUE ("contact_email"), CONSTRAINT "PK_3d02b3692836893720335a79d1b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_operators_name" ON "operators" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_operators_email" ON "operators" ("contact_email") `);
        await queryRunner.query(`CREATE INDEX "idx_operators_status" ON "operators" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_operators_name_status" ON "operators" ("name", "status") `);
        await queryRunner.query(`CREATE TYPE "public"."route_points_type_enum" AS ENUM('pickup', 'dropoff', 'both')`);
        await queryRunner.query(`CREATE TABLE "route_points" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying NOT NULL, "latitude" numeric(10,6) NOT NULL, "longitude" numeric(10,6) NOT NULL, "type" "public"."route_points_type_enum" NOT NULL DEFAULT 'both', "order" integer NOT NULL, "distanceFromStart" integer, "estimatedTimeFromStart" integer, "routeId" uuid NOT NULL, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_9684d129d71ff38906e7cb08c68" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "routes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "operator_id" uuid, "name" character varying NOT NULL, "description" character varying NOT NULL, "origin" character varying NOT NULL, "destination" character varying NOT NULL, "distance_km" numeric(8,2), "estimated_minutes" integer, "is_active" boolean NOT NULL DEFAULT true, "amenities" json, "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updatedAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_76100511cdfa1d013c859f01d8b" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "feedbacks" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "trip_id" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "submitted_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_79affc530fdd838a9f1e0cc30be" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "reviews" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "trip_id" uuid NOT NULL, "booking_id" uuid NOT NULL, "rating" integer NOT NULL, "comment" text, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bbd6ac6e3e6a8f8c6e0e8692d63" UNIQUE ("booking_id"), CONSTRAINT "UQ_booking_review" UNIQUE ("booking_id"), CONSTRAINT "PK_231ae565c273ee700b283f15c1d" PRIMARY KEY ("id")); COMMENT ON COLUMN "reviews"."rating" IS 'Rating from 1 to 5 stars'; COMMENT ON COLUMN "reviews"."comment" IS 'Optional review comment'`);
        await queryRunner.query(`CREATE INDEX "idx_reviews_user_id_single" ON "reviews" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_trip_id_single" ON "reviews" ("trip_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_booking_id" ON "reviews" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_created_at" ON "reviews" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_rating" ON "reviews" ("rating") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_trip_id" ON "reviews" ("trip_id") `);
        await queryRunner.query(`CREATE INDEX "idx_reviews_user_id" ON "reviews" ("user_id") `);
        await queryRunner.query(`CREATE TYPE "public"."trips_status_enum" AS ENUM('scheduled', 'in_progress', 'completed', 'cancelled', 'delayed')`);
        await queryRunner.query(`CREATE TABLE "trips" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "route_id" uuid NOT NULL, "bus_id" uuid NOT NULL, "departure_time" TIMESTAMP WITH TIME ZONE NOT NULL, "arrival_time" TIMESTAMP WITH TIME ZONE NOT NULL, "base_price" integer NOT NULL, "status" "public"."trips_status_enum" NOT NULL DEFAULT 'scheduled', "average_rating" numeric(3,2) NOT NULL DEFAULT '0', "review_count" integer NOT NULL DEFAULT '0', CONSTRAINT "PK_f71c231dee9c05a9522f9e840f5" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_trips_route_id" ON "trips" ("route_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_bus_id" ON "trips" ("bus_id") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_arrival_time" ON "trips" ("arrival_time") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_status" ON "trips" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_departure_time" ON "trips" ("departure_time") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_status_departure" ON "trips" ("status", "departure_time") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_bus_departure" ON "trips" ("bus_id", "departure_time") `);
        await queryRunner.query(`CREATE INDEX "idx_trips_route_departure" ON "trips" ("route_id", "departure_time") `);
        await queryRunner.query(`CREATE TABLE "passenger_details" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "full_name" character varying NOT NULL, "document_id" character varying, "seat_code" character varying NOT NULL, CONSTRAINT "PK_06422dddff22d9af8cf874c6d2e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."payments_status_enum" AS ENUM('pending', 'completed', 'failed', 'refunded', 'cancelled')`);
        await queryRunner.query(`CREATE TABLE "payments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "provider" character varying NOT NULL, "transaction_ref" character varying NOT NULL, "payos_order_code" integer, "amount" integer NOT NULL, "status" "public"."payments_status_enum" NOT NULL DEFAULT 'pending', "processed_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_197ab7af18c93fbb0c9b28b4a59" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_channel_enum" AS ENUM('email', 'sms', 'push', 'in_app')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'failed', 'delivered', 'read')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid, "user_id" uuid NOT NULL, "title" character varying, "message" character varying NOT NULL, "type" character varying, "data" jsonb, "channel" "public"."notifications_channel_enum" NOT NULL DEFAULT 'email', "template" character varying NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "sent_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."bookings_status_enum" AS ENUM('pending', 'paid', 'completed', 'cancelled', 'expired')`);
        await queryRunner.query(`CREATE TABLE "bookings" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_reference" character varying NOT NULL, "user_id" uuid, "trip_id" uuid NOT NULL, "total_amount" integer NOT NULL, "status" "public"."bookings_status_enum" NOT NULL DEFAULT 'pending', "contact_email" character varying, "contact_phone" character varying, "booked_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "last_modified_at" TIMESTAMP WITH TIME ZONE, "cancelled_at" TIMESTAMP WITH TIME ZONE, "expires_at" TIMESTAMP WITH TIME ZONE, CONSTRAINT "UQ_5ba137683172608bf22d69538a0" UNIQUE ("booking_reference"), CONSTRAINT "PK_bee6805982cc1e248e94ce94957" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_bookings_user_id" ON "bookings" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_trip_id" ON "bookings" ("trip_id") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_status" ON "bookings" ("status") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_status_expires_at" ON "bookings" ("status", "expires_at") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_booked_at" ON "bookings" ("booked_at") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_user_status" ON "bookings" ("user_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_trip_status" ON "bookings" ("trip_id", "status") `);
        await queryRunner.query(`CREATE INDEX "idx_bookings_user_trip" ON "bookings" ("user_id", "trip_id") `);
        await queryRunner.query(`CREATE TABLE "payment_methods" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "provider" character varying NOT NULL, "token" character varying NOT NULL, "is_default" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_34f9b8c6dfb4ac3559f7e2820d1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "token" character varying NOT NULL, "userId" uuid NOT NULL, "expiresAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TYPE "public"."users_role_enum" AS ENUM('admin', 'customer')`);
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "googleId" character varying, "facebookId" character varying, "email" character varying NOT NULL, "name" character varying NOT NULL, "phone" character varying, "password_hash" character varying NOT NULL, "role" "public"."users_role_enum" NOT NULL DEFAULT 'customer', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_f382af58ab36057334fb262efd5" UNIQUE ("googleId"), CONSTRAINT "UQ_f9740e1e654a5daddb82c60bd75" UNIQUE ("facebookId"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_users_google_id" ON "users" ("googleId") `);
        await queryRunner.query(`CREATE INDEX "idx_users_facebook_id" ON "users" ("facebookId") `);
        await queryRunner.query(`CREATE INDEX "idx_users_email" ON "users" ("email") `);
        await queryRunner.query(`CREATE INDEX "idx_users_name" ON "users" ("name") `);
        await queryRunner.query(`CREATE INDEX "idx_users_phone" ON "users" ("phone") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role" ON "users" ("role") `);
        await queryRunner.query(`CREATE INDEX "idx_users_role_created" ON "users" ("role", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."booking_modification_history_modification_type_enum" AS ENUM('passenger_info', 'seat_change', 'contact_info')`);
        await queryRunner.query(`CREATE TABLE "booking_modification_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "booking_id" uuid NOT NULL, "user_id" uuid, "modification_type" "public"."booking_modification_history_modification_type_enum" NOT NULL, "description" text NOT NULL, "changes" jsonb, "previousValues" jsonb, "modified_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_ef0cd664b4d69c6197502cbc8fb" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "idx_modification_history_booking_id" ON "booking_modification_history" ("booking_id") `);
        await queryRunner.query(`CREATE INDEX "idx_modification_history_type" ON "booking_modification_history" ("modification_type") `);
        await queryRunner.query(`CREATE INDEX "idx_modification_history_user" ON "booking_modification_history" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "idx_modification_history_booking" ON "booking_modification_history" ("booking_id") `);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "actor_id" uuid, "target_user_id" uuid, "action" character varying NOT NULL, "details" text, "metadata" jsonb, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "message" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "role" character varying NOT NULL, "content" text NOT NULL, "createdAt" TIMESTAMP NOT NULL DEFAULT now(), "conversationId" uuid, CONSTRAINT "PK_ba01f0a3e0123651915008bc578" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "conversation" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "title" character varying, CONSTRAINT "PK_864528ec4274360a40f66c29845" PRIMARY KEY ("id"))`);
        await queryRunner.query(`ALTER TABLE "seat_status" ADD CONSTRAINT "FK_e8a46b0dca3d048c97d74adfbe7" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seat_status" ADD CONSTRAINT "FK_40b48933387606c841426123cac" FOREIGN KEY ("seat_id") REFERENCES "seats"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seat_status" ADD CONSTRAINT "FK_85cb79c299aa3acb277ed736434" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seats" ADD CONSTRAINT "FK_63891430d84257508216445c058" FOREIGN KEY ("bus_id") REFERENCES "buses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "seat_layouts" ADD CONSTRAINT "FK_23691ddc597bf70420e511ab6c6" FOREIGN KEY ("bus_id") REFERENCES "buses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "buses" ADD CONSTRAINT "FK_a5d51574b60f8848d203e5f4241" FOREIGN KEY ("operator_id") REFERENCES "operators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "route_points" ADD CONSTRAINT "FK_a2eab28234f80f4a7962495d5b6" FOREIGN KEY ("routeId") REFERENCES "routes"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "routes" ADD CONSTRAINT "FK_699c50db7c54c0ef95c806abd7f" FOREIGN KEY ("operator_id") REFERENCES "operators"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedbacks" ADD CONSTRAINT "FK_4334f6be2d7d841a9d5205a100e" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "feedbacks" ADD CONSTRAINT "FK_62ff6a19bf6fc9e0770fe24c58d" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_362e169dcc383ce7bb4ddf021ff" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "reviews" ADD CONSTRAINT "FK_bbd6ac6e3e6a8f8c6e0e8692d63" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_e49dbbd9991c9b7baec9779e7ce" FOREIGN KEY ("route_id") REFERENCES "routes"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "trips" ADD CONSTRAINT "FK_de94f3218372c5bdfe1638c07c3" FOREIGN KEY ("bus_id") REFERENCES "buses"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "passenger_details" ADD CONSTRAINT "FK_0c19f8559ce0e7b47baa5455ad3" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payments" ADD CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_3f5c2196c2b2af99a4697e51741" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "notifications" ADD CONSTRAINT "FK_9a8a82462cab47c73d25f49261f" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_64cd97487c5c42806458ab5520c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "bookings" ADD CONSTRAINT "FK_45fa98a28a6944e39d8a5754bd1" FOREIGN KEY ("trip_id") REFERENCES "trips"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "payment_methods" ADD CONSTRAINT "FK_d7d7fb15569674aaadcfbc0428c" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" ADD CONSTRAINT "FK_610102b60fea1455310ccd299de" FOREIGN KEY ("userId") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_modification_history" ADD CONSTRAINT "FK_e4ad68fb61eb534643227fc2ef1" FOREIGN KEY ("booking_id") REFERENCES "bookings"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "booking_modification_history" ADD CONSTRAINT "FK_a27455dcc3340201583bc7491a6" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "message" ADD CONSTRAINT "FK_7cf4a4df1f2627f72bf6231635f" FOREIGN KEY ("conversationId") REFERENCES "conversation"("id") ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "message" DROP CONSTRAINT "FK_7cf4a4df1f2627f72bf6231635f"`);
        await queryRunner.query(`ALTER TABLE "booking_modification_history" DROP CONSTRAINT "FK_a27455dcc3340201583bc7491a6"`);
        await queryRunner.query(`ALTER TABLE "booking_modification_history" DROP CONSTRAINT "FK_e4ad68fb61eb534643227fc2ef1"`);
        await queryRunner.query(`ALTER TABLE "refresh_tokens" DROP CONSTRAINT "FK_610102b60fea1455310ccd299de"`);
        await queryRunner.query(`ALTER TABLE "payment_methods" DROP CONSTRAINT "FK_d7d7fb15569674aaadcfbc0428c"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_45fa98a28a6944e39d8a5754bd1"`);
        await queryRunner.query(`ALTER TABLE "bookings" DROP CONSTRAINT "FK_64cd97487c5c42806458ab5520c"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_9a8a82462cab47c73d25f49261f"`);
        await queryRunner.query(`ALTER TABLE "notifications" DROP CONSTRAINT "FK_3f5c2196c2b2af99a4697e51741"`);
        await queryRunner.query(`ALTER TABLE "payments" DROP CONSTRAINT "FK_e86edf76dc2424f123b9023a2b2"`);
        await queryRunner.query(`ALTER TABLE "passenger_details" DROP CONSTRAINT "FK_0c19f8559ce0e7b47baa5455ad3"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_de94f3218372c5bdfe1638c07c3"`);
        await queryRunner.query(`ALTER TABLE "trips" DROP CONSTRAINT "FK_e49dbbd9991c9b7baec9779e7ce"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_bbd6ac6e3e6a8f8c6e0e8692d63"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_362e169dcc383ce7bb4ddf021ff"`);
        await queryRunner.query(`ALTER TABLE "reviews" DROP CONSTRAINT "FK_728447781a30bc3fcfe5c2f1cdf"`);
        await queryRunner.query(`ALTER TABLE "feedbacks" DROP CONSTRAINT "FK_62ff6a19bf6fc9e0770fe24c58d"`);
        await queryRunner.query(`ALTER TABLE "feedbacks" DROP CONSTRAINT "FK_4334f6be2d7d841a9d5205a100e"`);
        await queryRunner.query(`ALTER TABLE "routes" DROP CONSTRAINT "FK_699c50db7c54c0ef95c806abd7f"`);
        await queryRunner.query(`ALTER TABLE "route_points" DROP CONSTRAINT "FK_a2eab28234f80f4a7962495d5b6"`);
        await queryRunner.query(`ALTER TABLE "buses" DROP CONSTRAINT "FK_a5d51574b60f8848d203e5f4241"`);
        await queryRunner.query(`ALTER TABLE "seat_layouts" DROP CONSTRAINT "FK_23691ddc597bf70420e511ab6c6"`);
        await queryRunner.query(`ALTER TABLE "seats" DROP CONSTRAINT "FK_63891430d84257508216445c058"`);
        await queryRunner.query(`ALTER TABLE "seat_status" DROP CONSTRAINT "FK_85cb79c299aa3acb277ed736434"`);
        await queryRunner.query(`ALTER TABLE "seat_status" DROP CONSTRAINT "FK_40b48933387606c841426123cac"`);
        await queryRunner.query(`ALTER TABLE "seat_status" DROP CONSTRAINT "FK_e8a46b0dca3d048c97d74adfbe7"`);
        await queryRunner.query(`DROP TABLE "conversation"`);
        await queryRunner.query(`DROP TABLE "message"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_history_booking"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_history_user"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_history_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_modification_history_booking_id"`);
        await queryRunner.query(`DROP TABLE "booking_modification_history"`);
        await queryRunner.query(`DROP TYPE "public"."booking_modification_history_modification_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role_created"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_role"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_phone"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_name"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_facebook_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_users_google_id"`);
        await queryRunner.query(`DROP TABLE "users"`);
        await queryRunner.query(`DROP TYPE "public"."users_role_enum"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP TABLE "payment_methods"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_user_trip"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_trip_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_user_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_booked_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_status_expires_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_trip_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_bookings_user_id"`);
        await queryRunner.query(`DROP TABLE "bookings"`);
        await queryRunner.query(`DROP TYPE "public"."bookings_status_enum"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_channel_enum"`);
        await queryRunner.query(`DROP TABLE "payments"`);
        await queryRunner.query(`DROP TYPE "public"."payments_status_enum"`);
        await queryRunner.query(`DROP TABLE "passenger_details"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_route_departure"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_bus_departure"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_status_departure"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_departure_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_arrival_time"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_bus_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_trips_route_id"`);
        await queryRunner.query(`DROP TABLE "trips"`);
        await queryRunner.query(`DROP TYPE "public"."trips_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_user_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_trip_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_rating"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_booking_id"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_trip_id_single"`);
        await queryRunner.query(`DROP INDEX "public"."idx_reviews_user_id_single"`);
        await queryRunner.query(`DROP TABLE "reviews"`);
        await queryRunner.query(`DROP TABLE "feedbacks"`);
        await queryRunner.query(`DROP TABLE "routes"`);
        await queryRunner.query(`DROP TABLE "route_points"`);
        await queryRunner.query(`DROP TYPE "public"."route_points_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_operators_name_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_operators_status"`);
        await queryRunner.query(`DROP INDEX "public"."idx_operators_email"`);
        await queryRunner.query(`DROP INDEX "public"."idx_operators_name"`);
        await queryRunner.query(`DROP TABLE "operators"`);
        await queryRunner.query(`DROP TYPE "public"."operators_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."idx_buses_operator_model"`);
        await queryRunner.query(`DROP INDEX "public"."idx_buses_operator_capacity"`);
        await queryRunner.query(`DROP INDEX "public"."idx_buses_model"`);
        await queryRunner.query(`DROP INDEX "public"."idx_buses_plate_number"`);
        await queryRunner.query(`DROP INDEX "public"."idx_buses_operator_id"`);
        await queryRunner.query(`DROP TABLE "buses"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seat_layouts_bus_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seat_layouts_created_at"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seat_layouts_type"`);
        await queryRunner.query(`DROP INDEX "public"."idx_seat_layouts_bus_id"`);
        await queryRunner.query(`DROP TABLE "seat_layouts"`);
        await queryRunner.query(`DROP TYPE "public"."seat_layouts_layouttype_enum"`);
        await queryRunner.query(`DROP TABLE "seats"`);
        await queryRunner.query(`DROP TYPE "public"."seats_seattype_enum"`);
        await queryRunner.query(`DROP TABLE "seat_status"`);
        await queryRunner.query(`DROP TYPE "public"."seat_status_state_enum"`);
    }

}
